### PR TITLE
Exported cogs failing

### LINKED ISSUE #546: Exported cogs failing
Exported cogs are failing in dev

### PR DESCRIPTION
**Pull request by osundwajeff**
Fixes #546 & #545

Screenshot From 2025-07-07 00-09-04

### CODE REVIEW

File: django_project/frontend/src/components/Map/LeftSide/Layers/index.tsx [hunk 1]
```diff
@@ -7,45 +9,104 @@ import {
...
+      copy.url = selectedLandscape.urls[layer.id];
+    }
+    dispatch(setSelectedNrtLayer(layer));
+    onLayerChecked(copy);
+  };
+
+  const showToast = (
+    title: string,
+    body: string,
+    status: "success" | "error"
```
Comment (dimasciput) [inline django_project/frontend/src/components/Map/LeftSide/Layers/index.tsx:63]: @osundwajeff it would be better to use enum for status I think

**Review by dimasciput — CHANGES_REQUESTED** [review]
